- name: Install Apache (httpd)
  yum:
    name: httpd
    state: present

- name: Copy custom index page
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: Ensure Apache is running and enabled
  service:
    name: httpd
    state: started
    enabled: yes
